@startuml

class Parser {
    + void next()
}

class Statement {
    + String type
    + Object value
}

class Configuration {
    - void add(File file)
    + String serialize()
}

Parser <-- Statement
Configuration <-- Parser
Configuration <-- Statement

@enduml
